apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/juank1400/myjupyternb.git
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: myjupyternb
    app.kubernetes.io/component: myjupyternb
    app.kubernetes.io/instance: myjupyternb
    app.kubernetes.io/name: myjupyternb
    app.kubernetes.io/part-of: Notebook
  name: myjupyternb
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: myjupyternb:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/juank1400/myjupyternb.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: myjupyternb-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: myjupyternb-github-webhook-secret
    type: GitHub
  - type: ConfigChange
