apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/juank1400/myjupyternb.git
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: myjupyternb
    app.kubernetes.io/component: myjupyternb
    app.kubernetes.io/instance: myjupyternb
    app.kubernetes.io/name: myjupyternb
    app.kubernetes.io/part-of: Notebook
  name: myjupyternb
spec:
  lookupPolicy:
    local: false
