apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/soft-25-01-g4/reto2.git
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: coordinador
    app.kubernetes.io/component: coordinador
    app.kubernetes.io/instance: coordinador
    app.kubernetes.io/name: coordinador
    app.kubernetes.io/part-of: reto-2
  name: coordinador
spec:
  lookupPolicy:
    local: false
